Add bloomchat 176b model
opentensor/miners pull request #2
Opened 2023-06-13 11:56 UTC by KMFODA

As per this bounty this is a draft PR to add multi gpu support to miners. This is achieved in one of two ways:

1. Using HuggingFace's accelerate which adopt a naive version of model parallelism using pipeline parallelism (PP)
2. Using DeepSpped inference which combines data parallelism, tensor parallelism and pipeline parallelism (DP + TP + PP)

This is still a WIP but a PR is being submitted to start testing and to gather thoughts of any eyes that fall on this.

2023-06-27 18:01 UTC, KMFODA commented
Hey, @ifrit98. I've now successfully tested running` tiiuae/falcon-40b-instruct`, `huggyllama/llama-65b `and `sambanovasystems/BLOOMChat-176B-v1 `on 4 and 8 GPUS using this PR using both accelerate and deepspeed so I'm converting this PR from draft to ready for review. 

Would appreciate any comments on if there's anything missing from this to enable merging! Thanks for all the help as always.

2023-06-28 15:06 UTC, ifrit98 requested changes
Small nits:
- add info about `bitsandbytes` in README for miners that use it
- delete uncommented code (don't modify anything in `base` unnecessarily

2023-06-28 15:06 UTC, ifrit98 commented on openminers/base/prompting_miner.py
Delete commented out code. Ideally we shouldn't modify the BasePromptingMiner unless absolutely necessary.

2023-06-28 15:06 UTC, ifrit98 commented on openminers/text_to_text/llama/README.md
Is it possible to add a little detail around `bitsandbytes`? Often this doesn't work out of the box and users may need to install from source.  Can you at least link to their repo to direct people in case they can't get pypi pkg to work?

2023-06-29 19:34 UTC, KMFODA commented on openminers/base/prompting_miner.py
Apologies, I had resorted to this as I couldn't run the miner locally otherwise. Deleted now thanks!

2023-06-29 19:35 UTC, KMFODA commented on openminers/text_to_text/llama/README.md
Yes for sure good point just added to all 3 READMEs!

2023-06-29 19:58 UTC, ifrit98 commented
@KMFODA Can you clean up these merge conflicts?

2023-06-30 11:51 UTC, KMFODA commented
@ifrit98 yes sure apologies didn't realise we're merging into staging. Done!

2023-06-30 16:29 UTC, ifrit98 approved these changes
LGTM!

2023-06-30 16:29 UTC, merged